name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: bash .\ci\windows\ci-windows.sh

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: brigadier-windows-exe
          path: D:\a\brigadier\brigadier\dist

      # Running the command as a test isn't really useful to us yet
      # - name: Test
      #   run: bash .\ci\windows\test.sh
